### ISSUE TITLE
Keep Kepler container image up to date

### ISSUE THREAD

**Issue by rootfs** [sustainable-computing-io/kepler#1047]
### What would you like to be added?

Some rpm packages used in the base images are subject to change. We should run `yum update` in the kepler image each time so to pick up the latest rpm packages.

For certain reason, adding `yum update -y` in the Kepler dockerfile runs into issues. Creating this issue to track the requirement

### Why is this needed?

Update rpms that are installed by the base image in Kepler image

**Comment by SamYuan1990** [comment]
break down:
1. make yum packages installed by yum repo so that yum update works.
2. make CI enable to build base image.
3. bump up base image with golang 1.21 with new CI.
4. bump up golang version to golang 1.21 in go mod.
5. bump up navida base image and try to merge navida's package version bump up(reported by dep bot.)
