### ISSUE TITLE
kepler metrics persistence between reboot

### ISSUE THREAD

**Issue by rootfs** [sustainable-computing-io/kepler#330]
- [ ] #305 
- [ ] deployment and doc update

**Comment by marceloamaral** [comment]
We had some discussion about this in the issue.

We are not sure if we really need this since what should persist the data is the data base (Prometheus in this case) and prometheus already has a good logic to deal with counters that were reset....
For example, other exporters, e.g. node_exporter does not persist the data.....

So, maybe persist the data is an overhead that might not be necessary....
