### ISSUE TITLE
Build manifest deployment with options

### ISSUE THREAD

**Issue by sunya-ch** [sustainable-computing-io/kepler#448]
**Is your feature request related to a problem? Please describe.**

- The current manifest build contains duplicating points separately for plain Kubernetes, OpenShift, VM, BM
- Adding integration of estimator sidecar and model server requires combination to the above duplication.
- Some setting such as image, namespace of users in rolebinding can be done more properly by kustomize instead of sed or manual change.

**Describe the solution you'd like**

The solution is to build manifest based on the same base defined patching and additional resources. 

**Describe alternatives you've considered**

**Additional context**

**Comment by jichenjc** [comment]
I think we covered this through #449 ?

**Comment by jichenjc** [comment]
seems https://sustainable-computing.io/installation/kepler/ is not updated, should we track here?

**Comment by sunya-ch** [comment]
Push the PR here https://github.com/sustainable-computing-io/kepler-doc/pull/33.

**Comment by nikimanoledaki** [comment]
Would it be okay if we only keep what is in the [installation docs](https://github.com/sustainable-computing-io/kepler-doc/blob/main/docs/installation/kepler.md) and add a link to it from `manifests/README.md` instead of duplicating instructions? 🤔 

That way there is a single source of truth for end-users. We then reduce the risk of having divergent installation instructions, one version being outdated, etc.
