### ISSUE TITLE
Security implications of enabling kernel-devel and pods mounting /sys/kernel/debug

### ISSUE THREAD

**Issue by BGrasnick** [sustainable-computing-io/kepler#771]
We want to install kepler (https://github.com/sustainable-computing-io/kepler/) in our OpenShift 4.10 cluster.

As a prerequisite for working on OpenShift, we need to enable kernel-devel on master and worker nodes:
https://github.com/sustainable-computing-io/kepler/blob/main/manifests/config/cluster-prereqs/51-master-kernel-devel.yaml
https://github.com/sustainable-computing-io/kepler/blob/main/manifests/config/cluster-prereqs/51-worker-kernel-devel.yaml

Also, we need to mount the debugFS (/sys/kernel/debug) into the kepler Pods:
https://github.com/sustainable-computing-io/kepler/blob/main/manifests/config/exporter/patch/patch-openshift.yaml

For usage on OpenShift, kepler also requires a very powerful SecurityContextConstraints giving itself extensive privileges:
https://github.com/sustainable-computing-io/kepler/blob/main/manifests/config/exporter/openshift_scc.yaml

After seeing all this, we grew a little concerned and were wondering if enabling all this could pose a security risk or impact cluster performance.

Could you provide some insight into these aspects and if it would be secure for us to make these changes and use kepler?

**Comment by rootfs** [comment]
Thank you @BGrasnick auditing all these issues. We are taking steps to remove these dependency:
- kernel-devel requirement. This requirement comes from bcc to dynamically compile ebpf module. After installing kernel-devel pkgs in Kepler container images, we no longer need it (but the manifest has not updated yet).
- `/sys/kernel/debug`. This is also from bcc library to dynamically resolve kernel data structure. @sunya-ch is adding libbpf option so that no more runtime data structure is needed in this [PR](https://github.com/sustainable-computing-io/kepler/pull/752)
- the powerful SCC indeed needs revisit. I think some of them can be removed (need to test though):
```
allowHostDirVolumePlugin: true
allowHostNetwork: true
allowHostPorts: true
allowHostIPC: true
```

**Comment by rootfs** [comment]
cc @vimalk78
